/* This file was generated by syncqt. */
#ifndef QT_QTFEEDBACK_VERSION_H
#define QT_QTFEEDBACK_VERSION_H

#define QTFEEDBACK_VERSION_STR "5.15.5"

#define QTFEEDBACK_VERSION 0x050F05

#endif // QT_QTFEEDBACK_VERSION_H
